[min_versions]
robotpy-build = "2023.0.0b14"

robotpy-wpiutil             = "2023.0.0b4"
pyntcore                    = "2023.0.0b4"
robotpy-hal                 = "2023.0.0b4"
robotpy-wpimath             = "2023.0.0b4"
wpilib                      = "2023.0.0b4"
robotpy-halsim-gui          = "2023.0.0b4"
robotpy-halsim-ds-socket    = "2023.0.0b4"
robotpy-halsim-ws           = "2023.0.0b4"

[versions]
robotpy-wpiutil             = "2023.0.0b4"
robotpy-wpinet              = "2023.0.0b4"
pyntcore                    = "2023.0.0b4"
robotpy-hal                 = "2023.0.0b4"
robotpy-wpimath             = "2023.0.0b4"
wpilib                      = "2023.0.0b4"
robotpy-halsim-gui          = "2023.0.0b4"
robotpy-halsim-ds-socket    = "2023.0.0b4"
robotpy-halsim-ws           = "2023.0.0b4"
robotpy-commands-v2         = "2023.0.0b4"

robotpy-navx                = "2022.0.2"
robotpy-ctre                = "2022.1.0"
robotpy-playingwithfusion   = "2022.0.4"
robotpy-rev                 = "2022.0.1"
robotpy-romi                = "2022.2.1.0"
robotpy-photonvision        = "2022.0.3"

[params]
max_version = "2024.0.0"
wpilib_version = "2023.1.1-beta-4"
wpilib_packages = [
    "robotpy-wpiutil",
    "robotpy-wpinet",
    "pyntcore",
    "robotpy-hal",
    "robotpy-wpimath",
    "wpilib",
    "robotpy-halsim-gui",
    "robotpy-halsim-ds-socket",
    "robotpy-halsim-ws",
    "robotpy-commands-v2",
]

vendor_packages = [
    "robotpy-navx",
    "robotpy-rev",
    "robotpy-ctre",
    "robotpy-playingwithfusion",
    "robotpy-photonvision",
    "robotpy-romi",
]

repos = [
    "https://github.com/robotpy/robotpy-wpiutil",
    "https://github.com/robotpy/robotpy-wpinet",
    "https://github.com/robotpy/pyntcore",
    "https://github.com/robotpy/robotpy-hal",
    "https://github.com/robotpy/robotpy-wpimath",
    "https://github.com/robotpy/robotpy-wpilib",
    "https://github.com/robotpy/robotpy-halsim-gui",
    "https://github.com/robotpy/robotpy-halsim-ds-socket",
    "https://github.com/robotpy/robotpy-halsim-ws",
    "https://github.com/robotpy/robotpy-commands-v2",
    "https://github.com/robotpy/robotpy-romi",
    "https://github.com/robotpy/robotpy-navx",
    "https://github.com/robotpy/robotpy-ctre",
    "https://github.com/robotpy/robotpy-rev",
    "https://github.com/robotpy/robotpy-playingwithfusion",
    "https://github.com/robotpy/robotpy-photonvision",
]
